apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gc-articles
  title: GC Articles
  description: Content management system run for CDS products.  It uses Wordpress as the underlying service.
  annotations:
    github.com/project-slug: cds-snc/gc-articles
spec:
  type: service
  lifecycle: production
  owner: group:cds-snc/platform-core
  system: websites

