import './insert-alert-block';
import './select-alert-block';
import './visit-dashboard';
import './visit-notify';
import './visit-profile';
import './add-user';
import './login-user';
import './add-user-cap';
import './test-setup';
