name: "Deploy PRODUCTION container"

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/environments.yml"
  pull_request:
    branches:
      - main
    paths:
      - "infrastructure/environments.yml"

env:
  AWS_REGION: ca-central-1

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  environments-manifest:
    uses: cds-snc/gc-articles/.github/workflows/environments-manifest.yml@main

  deployment-preview:
    needs: environments-manifest
    runs-on: ubuntu-latest

    if: |
      github.ref != 'refs/heads/main' &&
      github.event_name == 'pull_request' &&
      needs.environments-manifest.outputs.CONTAINER_DEPLOYMENT == 'production'

    steps:
      - name: Post deployment preview
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `## Production: container deployment preview
            | Container | Version |
            |-----------|---------|
            | WordPress | \`v${{ needs.environments-manifest.outputs.PROD_WORDPRESS }}\` |
            | Apache    | \`v${{ needs.environments-manifest.outputs.PROD_APACHE }}\` |`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

  deploy-production:
    needs: environments-manifest
    runs-on: ubuntu-latest

    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      needs.environments-manifest.outputs.CONTAINER_DEPLOYMENT == 'production'

    env:
      APACHE_VERSION: ${{ needs.environments-manifest.outputs.PROD_APACHE }}
      WORDPRESS_VERSION: ${{ needs.environments-manifest.outputs.PROD_WORDPRESS }}
      ECR_REGISTRY: 472286471787.dkr.ecr.ca-central-1.amazonaws.com

    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::472286471787:role/gc-articles-docker-deploy
          role-session-name: ECSDeployProduction
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition wordpress --query taskDefinition > task-definition.json

      - name: Render wordpress container image
        id: render-wordpress
        uses: aws-actions/amazon-ecs-render-task-definition@6853cfae8c3a7d978fbf68b5a55453395541dfbb # v1
        with:
          task-definition: task-definition.json
          container-name: wordpress
          image: ${{ env.ECR_REGISTRY }}/platform/wordpress:v${{ env.WORDPRESS_VERSION }}

      - name: Render apache container image
        id: render-apache
        uses: aws-actions/amazon-ecs-render-task-definition@6853cfae8c3a7d978fbf68b5a55453395541dfbb # v1
        with:
          task-definition: ${{ steps.render-wordpress.outputs.task-definition }}
          container-name: apache
          image: ${{ env.ECR_REGISTRY }}/platform/apache:v${{ env.APACHE_VERSION }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c # v2
        with:
          task-definition: ${{ steps.render-apache.outputs.task-definition }}
          service: wordpress
          cluster: wordpress

      - name: Post to slack
        if: success()
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":lapage: New GC Articles <https://github.com/cds-snc/gc-articles/commit/${{ github.sha }}|release has been deployed>!"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_WEBSITE_INFINITE }}

      - name: Report deployment to Sentinel
        if: always()
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          input_data: '{"product": "articles", "sha": "${{ github.sha }}", "version": "Apache ${{ env.APACHE_VERSION }}, Wordpress ${{ env.WORDPRESS_VERSION }}", "repository": "${{ github.repository }}", "environment": "production", "status": "${{ job.status }}"}'
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
