name: "Terragrunt deploy PRODUCTION container"

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/environments.yml"
  pull_request:
    branches:
      - main
    paths:
      - "infrastructure/environments.yml"

env:
  AWS_REGION: ca-central-1
  TF_INPUT: false
  TF_VAR_database_name: ${{ secrets.PRODUCTION_DATABASE_NAME }}
  TF_VAR_database_username: ${{ secrets.PRODUCTION_DATABASE_USERNAME }}
  TF_VAR_database_password: ${{ secrets.PRODUCTION_DATABASE_PASSWORD }}
  TF_VAR_default_notify_api_key: ${{ secrets.PRODUCTION_DEFAULT_NOTIFY_API_KEY }}
  TF_VAR_encryption_key: ${{ secrets.PRODUCTION_ENCRYPTION_KEY }}
  TF_VAR_s3_uploads_bucket: ${{ secrets.PRODUCTION_S3_UPLOADS_BUCKET }}
  TF_VAR_s3_uploads_key: ${{ secrets.PRODUCTION_S3_UPLOADS_KEY }}
  TF_VAR_s3_uploads_secret: ${{ secrets.PRODUCTION_S3_UPLOADS_SECRET }}
  TF_VAR_c3_aws_access_key_id: ${{ secrets.PRODUCTION_C3_AWS_ACCESS_KEY_ID }}
  TF_VAR_c3_aws_secret_access_key: ${{ secrets.PRODUCTION_C3_AWS_SECRET_ACCESS_KEY }}
  TF_VAR_sentinel_customer_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  TF_VAR_sentinel_shared_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
  TF_VAR_slack_webhook_url: ${{ secrets.PRODUCTION_SLACK_WEBHOOK_URL }}
  TF_VAR_wordpress_auth_key: ${{ secrets.PRODUCTION_WORDPRESS_AUTH_KEY }}
  TF_VAR_wordpress_secure_auth_key: ${{ secrets.PRODUCTION_WORDPRESS_SECURE_AUTH_KEY }}
  TF_VAR_wordpress_logged_in_key: ${{ secrets.PRODUCTION_WORDPRESS_LOGGED_IN_KEY }}
  TF_VAR_wordpress_nonce_key: ${{ secrets.PRODUCTION_WORDPRESS_NONCE_KEY }}
  TF_VAR_wordpress_auth_salt: ${{ secrets.PRODUCTION_WORDPRESS_AUTH_SALT }}
  TF_VAR_wordpress_secure_auth_salt: ${{ secrets.PRODUCTION_WORDPRESS_SECURE_AUTH_SALT }}
  TF_VAR_wordpress_logged_in_salt: ${{ secrets.PRODUCTION_WORDPRESS_LOGGED_IN_SALT }}
  TF_VAR_wordpress_nonce_salt: ${{ secrets.PRODUCTION_WORDPRESS_NONCE_SALT }}
  TF_VAR_jwt_auth_secret_key: ${{ secrets.PRODUCTION_JWT_AUTH_SECRET_KEY }}
  TF_VAR_wpml_site_key: ${{ secrets.PRODUCTION_WPML_SITE_KEY }}
  TF_VAR_zendesk_api_url: ${{ secrets.ZENDESK_API_URL }}

permissions: {}

jobs:
  environments-manifest:
    permissions:
      contents: read
    uses: ./.github/workflows/environments-manifest.yml

  terragrunt-plan-production:
    needs: environments-manifest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    if: |
      github.ref != 'refs/heads/main' &&
      github.event_name == 'pull_request' &&
      needs.environments-manifest.outputs.CONTAINER_DEPLOYMENT == 'production'

    env:
      TARGET_VERSION: ${{ needs.environments-manifest.outputs.PROD_INFRASTRUCTURE }}

    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@36df0d7572a15921998170395475093c183d720a # v1.3.0
        env:
          CONFTEST_VERSION: 0.36.0 
          CONFTEST_CHECKSUM: d98783276c4fd47c779a1ece4c0decba9ee6462687839d25389882a468c362cc
          TERRAFORM_VERSION: 1.15.5
          TERRAFORM_CHECKSUM: 702b2136af6728c8ff037f843dd2dbce2b7ad88786b7381d1d72aefa250f601c
          TERRAGRUNT_VERSION: 1.0.4
          TERRAGRUNT_CHECKSUM: 387509aa15d3f38a93d0888ace2bd67c3e5eea841e1f4d585ea2174d566f35e9
          TF_SUMMARIZE_VERSION: 0.3.5
          TF_SUMMARIZE_CHECKSUM: e0ea7b514f7a57a85e5e4594acdccbf2dce3af7e00fe90580b2ad9cc1288d317
          TRUFFLEHOG_VERSION: NONE

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: arn:aws:iam::472286471787:role/gc-articles-plan
          role-session-name: TFPlanECS
          aws-region: ${{ env.AWS_REGION }}

      # Load-balancer & database dependency
      - name: Terragrunt plan ecs
        if: ${{ needs.environments-manifest.outputs.CONTAINER_DEPLOYMENT == 'production' }}
        uses: cds-snc/terraform-plan@529b272050a8f718d14c59e62b59c124eead7efc # v5.0.4
        with:
          directory: "infrastructure/terragrunt/env/prod/ecs"
          comment-delete: "true"
          comment-title: "Production: ecs"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

  terragrunt-apply-production:
    needs: environments-manifest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      needs.environments-manifest.outputs.CONTAINER_DEPLOYMENT == 'production'

    env:
      APACHE_VERSION: ${{ needs.environments-manifest.outputs.PROD_APACHE }}
      TARGET_VERSION: ${{ needs.environments-manifest.outputs.PROD_INFRASTRUCTURE }}
      WORDPRESS_VERSION: ${{ needs.environments-manifest.outputs.PROD_WORDPRESS }}

    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@36df0d7572a15921998170395475093c183d720a # v1.3.0
        env:
          CONFTEST_VERSION: NONE
          TERRAFORM_VERSION: 1.15.5
          TERRAFORM_CHECKSUM: 702b2136af6728c8ff037f843dd2dbce2b7ad88786b7381d1d72aefa250f601c
          TERRAGRUNT_VERSION: 1.0.4
          TERRAGRUNT_CHECKSUM: 387509aa15d3f38a93d0888ace2bd67c3e5eea841e1f4d585ea2174d566f35e9
          TF_SUMMARIZE_VERSION: NONE
          TRUFFLEHOG_VERSION: NONE

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: arn:aws:iam::472286471787:role/gc-articles-apply
          role-session-name: TFApplyECS
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt apply ecs
        working-directory: infrastructure/terragrunt/env/prod/ecs
        run: terragrunt run -non-interactive -- apply -auto-approve

      - name: Post to slack
        if: success()
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":lapage: New GC Articles <https://github.com/cds-snc/gc-articles/commit/${{ github.sha }}|release has been deployed>!"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_WEBSITE_INFINITE }}

      - name: Report deployment to Sentinel
        if: always()
        uses: cds-snc/sentinel-forward-data-action@e358bf24b818e68a22c9736715a3b544851aaba8
        with:
          input_data: '{"product": "articles", "sha": "${{ github.sha }}", "version": "Apache ${{ env.APACHE_VERSION }}, Wordpress ${{ env.WORDPRESS_VERSION }}", "repository": "${{ github.repository }}", "environment": "production", "status": "${{ job.status }}"}'
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
