name: "Terragrunt apply STAGING"

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/terragrunt/aws/**"
      - "infrastructure/terragrunt/env/staging/**"
      - "infrastructure/terragrunt/env/common/**"
      - "infrastructure/terragrunt/env/terragrunt.hcl"
      - ".github/workflows/terragrunt-apply-staging.yml"

env:
  AWS_REGION: ca-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.0.2
  TERRAGRUNT_VERSION: 0.31.0
  TF_INPUT: false
  TF_VAR_database_name: ${{ secrets.STAGING_DATABASE_NAME }}
  TF_VAR_database_username: ${{ secrets.STAGING_DATABASE_USERNAME }}
  TF_VAR_database_password: ${{ secrets.STAGING_DATABASE_PASSWORD }}
  TF_VAR_cloudfront_custom_header_name: ${{ secrets.STAGING_CLOUDFRONT_CUSTOM_HEADER_NAME }}
  TF_VAR_cloudfront_custom_header_value: ${{ secrets.STAGING_CLOUDFRONT_CUSTOM_HEADER_VALUE }}
  TF_VAR_list_manager_endpoint: ${{ secrets.STAGING_LIST_MANAGER_ENDPOINT }}
  TF_VAR_list_manager_api_key: ${{ secrets.STAGING_LIST_MANAGER_API_KEY }}
  TF_VAR_default_notify_api_key: ${{ secrets.STAGING_DEFAULT_NOTIFY_API_KEY }}
  TF_VAR_encryption_key: ${{ secrets.STAGING_ENCRYPTION_KEY }}
  TF_VAR_s3_uploads_bucket: ${{ secrets.STAGING_S3_UPLOADS_BUCKET }}
  TF_VAR_s3_uploads_key: ${{ secrets.STAGING_S3_UPLOADS_KEY }}
  TF_VAR_s3_uploads_secret: ${{ secrets.STAGING_S3_UPLOADS_SECRET }}
  TF_VAR_slack_webhook_url: ${{ secrets.STAGING_SLACK_WEBHOOK_URL }}
  TF_VAR_wordpress_auth_key: ${{ secrets.STAGING_WORDPRESS_AUTH_KEY }}
  TF_VAR_wordpress_secure_auth_key: ${{ secrets.STAGING_WORDPRESS_SECURE_AUTH_KEY }}
  TF_VAR_wordpress_logged_in_key: ${{ secrets.STAGING_WORDPRESS_LOGGED_IN_KEY }}
  TF_VAR_wordpress_nonce_key: ${{ secrets.STAGING_WORDPRESS_NONCE_KEY }}
  TF_VAR_wordpress_auth_salt: ${{ secrets.STAGING_WORDPRESS_AUTH_SALT }}
  TF_VAR_wordpress_secure_auth_salt: ${{ secrets.STAGING_WORDPRESS_SECURE_AUTH_SALT }}
  TF_VAR_wordpress_logged_in_salt: ${{ secrets.STAGING_WORDPRESS_LOGGED_IN_SALT }}
  TF_VAR_wordpress_nonce_salt: ${{ secrets.STAGING_WORDPRESS_NONCE_SALT }}

jobs:
  terragrunt-apply-staging:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # v1.3.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/*
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: filter
        with:
          filters: |
            common:
              - '.github/workflows/terragrunt-apply-staging.yml'
              - 'infrastructure/terragrunt/env/common/**'
              - 'infrastructure/terragrunt/env/terragrunt.hcl'
              - 'infrastructure/terragrunt/env/staging/env_vars.hcl'
            alarms:
              - 'infrastructure/terragrunt/aws/alarms/**'
              - 'infrastructure/terragrunt/env/staging/alarms/**'
            database:
              - 'infrastructure/terragrunt/aws/database/**'
              - 'infrastructure/terragrunt/env/staging/database/**'
            ecr:
              - 'infrastructure/terragrunt/aws/ecr/**'
              - 'infrastructure/terragrunt/env/staging/ecr/**'
            ecs:
              - 'infrastructure/terragrunt/aws/ecs/**'
              - 'infrastructure/terragrunt/env/staging/ecs/**'
            hosted-zone:
              - 'infrastructure/terragrunt/aws/hosted-zone/**'
              - 'infrastructure/terragrunt/env/staging/hosted-zone/**'
            load-balancer:
              - 'infrastructure/terragrunt/aws/load-balancer/**'
              - 'infrastructure/terragrunt/env/staging/load-balancer/**'
            network:
              - 'infrastructure/terragrunt/aws/network/**'
              - 'infrastructure/terragrunt/env/staging/network/**'
            storage:
              - 'infrastructure/terragrunt/aws/storage/**'
              - 'infrastructure/terragrunt/env/staging/storage/**'

      # No dependencies
      - name: Terragrunt apply network
        if: ${{ steps.filter.outputs.network == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/network
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply hosted-zone
        if: ${{ steps.filter.outputs.hosted-zone == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/hosted-zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply ecr
        if: ${{ steps.filter.outputs.ecr == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/ecr
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply storage
        if: ${{ steps.filter.outputs.storage == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/storage
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      # Network dependency
      - name: Terragrunt apply database
        if: ${{ steps.filter.outputs.database == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/database
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply load-balancer
        if: ${{ steps.filter.outputs.load-balancer == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/load-balancer
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      # Load-balancer & database dependency
      - name: Terragrunt apply ecs
        if: ${{ steps.filter.outputs.ecs == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/ecs
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      # Depends on everything
      - name: Terragrunt apply alarms
        if: ${{ steps.filter.outputs.alarms == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: infrastructure/terragrunt/env/staging/alarms
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

